//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirFranceCompagnie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vol
    {
        public System.Guid IdVol { get; set; }
        public System.DateTime DateDepart { get; set; }
        public Nullable<System.DateTime> DateArrive { get; set; }
        public Nullable<System.Guid> IdAvion { get; set; }
        public Nullable<System.Guid> IdPilote { get; set; }
        public string LieuDepart { get; set; }
        public string LieuArrivee { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Pilote Pilote { get; set; }
    }
}
